FROM python:3.10-alpine

WORKDIR /usr/src/app

COPY requirements.txt requirements.txt

RUN pip install --no-cache -r requirements.txt

COPY . .

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "main:app"]

EXPOSE 8000