apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: vurc/signdetectweb
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
          - name: API_ADDRESS
            value: http://api-service:8000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web
spec:
  # type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: web