apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: vurc/signdetect
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: DB_PASSWORD
          - name: POSTGRES_DATABASE_URL
            value: postgresql://$(DB_USER):$(DB_PASSWORD)@postgres:5432/postgres
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: JWT_SECRET
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  # type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: api