apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  labels:
    app: api
stringData:
  DB_USER: postgres
  DB_PASSWORD: pass
  JWT_SECRET: 5d609ed8d4efab2d4766df7fe0d039b2769d9065b64faca510615aa77aa9efbb
