apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-ceph-ssd-ms1
  resources:
    requests:
      storage: 1Gi