apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-ceph-ssd-ms1
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      imagePullSecrets:
        - name: k8s-registry-creds
      containers:
        - name: postgres
          image: '212.233.122.47:5000/post:15'
          ports:
            - containerPort: 5432
          env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: POSTGRES_USER
                optional: false
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: POSTGRES_PASSWORD
                optional: false
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: POSTGRES_DB
                optional: false
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/pgdata
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres